## Documentation

Hola Víctor, en el zip tienes archivos de un total de 20 cuencas en la cuenca del Ebro
Anduña, Bailin, Deza, Flamisell, Garona, Isuela, Larraun, Nela,
Oroncillo, Rudron, Sangüesa, Subialde, Tiron, Trueba, Ubagua, Urrobi,
Vallfarrera, Yanguas, Zatoya, Zidacos.

Hay tres archivos por cuenca con la misma estructura de nombres (puedes mecanizar su lectura usando la lista anterior):

1. Archivo con datos de clima y aforo "Anduña_2020_2025.csv" (usaré
Anduña como ejemplo pero solo tienes que sustituir el nombre de la
cuenca) con datos climatológicos, de nivel y aforo. Tiene los siguientes
datos diarios desde el 1 de octubre de 2020 hasta el 30 de septiembre de
2020:
Province,
Station,
Date,
Year,
Jdate,
tav (tempoeratura media),
tmax (temperatura máxima),
tmin (temperatura mínima),
Hrav (humedad relativa media),
Hrmax (humedad relativa máxima),
Hrmin (humedad relativa mínima),
wv (velocidad del viento),
wvmax (velocidad del viento máxima racha),
SolarRad (radiación solar),
Psiar (precipitación, no tener en cuenta, le faltan muchos datos),
EffPsiar (precipitación efectiva, no tener en cuenta, le faltan muchos datos),
et0 (evapotranspiración potencial), P (precipitación),
ymin (nivel medido en aforo, mínimo),
yav (nivel medido en aforo, medio),
ymax (nivel medido en aforo, máximo),
qmin (caudal medido en aforo, mínimo),
qav (nivel medido en aforo, medio),
qmax (nivel medido en aforo, máximo).

2. Archivo con datos de propiedades físicas de la cuenca
"Anduña_physics.csv": Hay información de las propiedades físicas de la
cuenca: CN_ponderado (promedio del núemro de curva),
CN_DT (desviación típica del número de curva),
area_cuenca (área de la cuenca),
longitud_total (longitud del cauce principal),
z_min (cota mínima de la cuenca),
z_max (cota máxima de la cuenca),
mean_sand (porcentaje promedio de la fracción arena del suelo),
mean_silt (porcentaje promedio de la fracción limo del suelo),
mean_clay (porcentaje promedio de la fracción arcilla del suelo),
soil_type (clase textural del suelo),
ks_st (conductividad hidráulica de la clase textural seleccionada),
thetas_st (contenido de humedad a saturación de la clase textural seleccionada),
thetar_st (contenido en humedad residual de la clase textural seleccionada),
thau_st (succión en el frente de avance de la clase textural seleccionada),
swcfc_st (contenido de humedad a capacidad de campo de la clase textural seleccionada),
swcpwp_st (contenido de humedad en el punto de marchitez permanente de la clase textural seleccionada),
mean_ks (conductividad hidráulica promedio de todos los píxeles),
DT_ks (desviación típica conductividad hidráulica de todos los píxeles),
mean_thetas (contenido de humedad a saturación promedio de todos los píxeles),
DT_thetas (desviación típica contenido de humedad a saturación de todos los píxeles),
mean_thetar (contenido de humedad residual promedio de todos los píxeles),
DT_thetar (desviación típica contenido de humedad residual de todos los píxeles),
mean_thau (succión en el frente de avance promedio de todos los píxeles),
DT_thau (desviación típica succión en el frente de avance de todos los píxeles),
mean_swcfc (contenido de humedad a capacidad de campo promedio de todos los píxeles),
DT_swcfc (desviación típica contenido de humedad a capacidad de campo de todos los píxeles),
mean_swcpwp (contenido de humedad punto de marchitez permanente promedio de todos los píxeles),
DT_swcpwp (desviación típica contenido de humedad punto de marchitez permanente de todos los píxeles),
lon_min (coordenada longitud mínima de cualquier punto de la cuenca),
lon_max (coordenada longitud máxima de cualquier punto de la cuenca),
lat_min (coordenada latitud mínima de cualquier punto de la cuenca),
lat_max (coordenada latitud máxima de cualquier punto de la cuenca)

3. Archivos con contenido de humedad en el suelo "SMAnduña_physics.csv".
Incluye (OJO AQUÍ EMPIEZAN LOS DATOS EL 30/09/2020 POR ERROR MÍO, OBVIA
EL PRIMERO):
día,
tipo AM (mañana) o PM (noche)
latitude,
longitude,
soil_moisture (humedad).


Voy a simplificar al máximo para que podamos empezar a trabajar con
midiendo los pasos.
1. Los archivos 1 y 3 tienen series temporales, el archivo 2 parámetros
físicos que son específicos de cada cuenca, no dependen del tiempo.
2. El objetivo será predecir el caudal (lo tienes en el archivo 1) y
tenemos que ver si con este tipo de información somos capaces de
predecir mejor el mínimo (qmin), el promedio (qav) o el máximo (qmax)
3. Hacemos análisis exploratorio  buscando correlaciones entre esos
caudales y las siguientes variables de forma aislada:

   3.a) Del archivo 1 (por cuencas y agregando todos los datos de todas las
cuencas): tav, tmax, tmin, Hrav, Hrmax, Hrmin, wv, wvmax, SolarRad, et0.

   3.b) Del archivo 3: soil_moisture AM, soil_moisture PM (ten en cuenta
que en cada csv hay por cada día una fila con AM y otra con PM, si
prefieres que te lo organice de otra forma para que te sea más fácil
dímelo), promedio de los dos anteriores.
4. Hacemos un primer tanteo de agrupar estaciones a la vista del caudal
y repetir el paso 3 para los clústers que salgan.
5. Repetimos los pasos 3 y 4 por meses (puedes usar el Jdate para
filtrar por meses).
6. Empezamos con los modelos predictivos por cuencas del más sencillo al
más complejo:
    6.a)  q=f(p), para los tres caudales y con la precipitación, prueba los
modelos que quieras.
    6.b)  q=f(p,soil_moisture), para los tres caudales y con la
precipitación, prueba modelos.

Creo que es buen punto de partida, hasta dónde crees que te da tiempo a
llegar de aquí al viernes?

Rafael, sírvete a tu gusto :-) y cualquier comentario desde luego es
bienvenido.


Deberíamos crear un documento en el que pudiéramos ir escribiendo lo que
hacemos (empezando por el contenido de este mail y yo iré actualizando
con los métodos que he empleado para sacar los datos). Google no me
gusta mucho pero si es el que usas me apaño. Si hay otras opciones por
mí casi mejor (conoces overleaf?).


--
SERGIO ZUBELZU MINGUEZ
Hidráulica, Hidrología y Riegos  (Departamento de Ingeniería
Agroforestal)
Universidad Politécnica de Madrid

## Imports

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import json
import os
import pandas as pd
import seaborn as sns

# Mostrar todas las columnas
pd.set_option("display.max_columns", None)

# (Opcional) Mostrar todas las filas
#pd.set_option("display.max_rows", None)

# (Opcional) Ajustar el ancho de cada columna para que no se corte
pd.set_option("display.max_colwidth", None)


import warnings
warnings.filterwarnings("ignore", message="Could not infer format")

In [2]:
ls ../../data/raw

climate_archive/             smap_archive/
old/                         soil_moisture_archive/
physical_properties_archive/ trash/

## Basins list (manual)

In [3]:
basins = ["Anduña","Bailin","Deza","Flamisell","Garona","Isuela","Larraun",
          "Nela","Oroncillo","Rudron","Sangüesa","Subialde","Tiron",
          #"Trueba",
          "Ubagua","Urrobi","Vallfarrera",
          "Yanguas",# Missing Date column
          "Zatoya",
          #"Zidacos"
         ]

## Read data

dtype_climate_dict = {
    'Province': 'string',
    'Station': 'string',
    'Date': 'string',  # Se parsea con `parse_dates`, pero aquí puede ir como string
    'Year': 'string',
    'Jdate': 'string',
    'tav': 'string',
    'tmax': 'string',
    'tmin': 'string',
    'Hrav': 'string',
    'Hrmax': 'string',
    'Hrmin': 'string',
    'wv': 'string',
    'wvmax': 'string',
    'SolarRad': 'string',
    'Psiar': 'string',
    'EffPsiar': 'string',
    'et0': 'string',
    'P': 'string',
    'ymin': 'string',
    'yav': 'string',
    'ymax': 'string',
    'qmin': 'string',
    'qav': 'string',
    'qmax': 'string'
}

In [4]:
def coma_to_float(x):
    try:
        return float(x.replace(",", "."))
    except:
        return np.nan  # pd.NA  or np.nan

In [5]:
converters_climate = {
    'tav': coma_to_float,
    'tmax': coma_to_float,
    'tmin': coma_to_float,
    'Hrav': coma_to_float,
    'Hrmax': coma_to_float,
    'Hrmin': coma_to_float,
    'wv': coma_to_float,
    'wvmax': coma_to_float,
    'SolarRad': coma_to_float,
    'Psiar': coma_to_float,
    'EffPsiar': coma_to_float,
    'et0': coma_to_float,
    'P': coma_to_float,
    'ymin': coma_to_float,
    'yav': coma_to_float,
    'ymax': coma_to_float,
    'qmin': coma_to_float,
    'qav': coma_to_float,
    'qmax': coma_to_float
}

In [6]:
climate_dict = {
    b: pd.read_csv(
        f"../../data/raw/climate_archive/{b}_2020_2025.csv",
        sep=";",
        parse_dates=["Date"],
        date_format={'Date': '%d/%m/%Y'},
        converters=converters_climate
    )
    for b in basins
}

In [7]:

#Fix different date fomats:

for k, v in climate_dict.items():
    climate_dict[k]["Date"] = pd.to_datetime(climate_dict[k]["Date"], dayfirst=True, errors="coerce")

In [8]:
len(climate_dict["Anduña"])

1826

In [9]:
len(climate_dict["Isuela"])

1826

In [10]:
physical_dict = {b: pd.read_csv(f"../../data/raw/physical_properties_archive/{b}_physics.csv", sep=",") for b in basins}

In [11]:
# EXCLUDED 2026-03-23:

# humidity_dict = {b: pd.read_csv(f"../../data/raw/soil_moisture_archive/SM{b}_physics.csv", sep=",", parse_dates=["dia"]) for b in basins}

In [12]:
smap_dict = {b: pd.read_csv(f"../../data/raw/smap_archive/{b}_SM_av_dif.csv", sep=",", parse_dates=["date"]) for b in basins}

In [13]:
len(physical_dict["Anduña"])

1

In [14]:
len(physical_dict["Isuela"])

1

In [15]:
#len(humidity_dict["Anduña"])

In [16]:
len(smap_dict["Anduña"])

1826

In [17]:
len(smap_dict["Isuela"])

1826

## Check column names

In [18]:
climate_dict[basins[0]].columns

Index(['Province', 'Station', 'Date', 'Year', 'Jdate', 'tav', 'tmax', 'tmin',
       'Hrav', 'Hrmax', 'Hrmin', 'wv', 'wvmax', 'SolarRad', 'Psiar',
       'EffPsiar', 'et0', 'P', 'ymin', 'yav', 'ymax', 'qmin', 'qav', 'qmax'],
      dtype='object')

In [19]:
physical_dict[basins[0]].columns

Index(['CN_ponderado', 'CN_DT', 'n', 'DT_n', 'area_cuenca', 'longitud_total',
       'z_min', 'z_max', 'mean_sand', 'mean_silt', 'mean_clay', 'soil_type',
       'ks_st', 'thetas_st', 'thetar_st', 'thau_st', 'swcfc_st', 'swcpwp_st',
       'mean_ks', 'DT_ks', 'mean_thetas', 'DT_thetas', 'mean_thetar',
       'DT_thetar', 'mean_thau', 'DT_thau', 'mean_swcfc', 'DT_swcfc',
       'mean_swcpwp', 'DT_swcpwp', 'lon_min', 'lon_max', 'lat_min', 'lat_max',
       'x_min_25830', 'x_max_25830', 'y_min_25830', 'y_max_25830'],
      dtype='object')

In [20]:
#humidity_dict[basins[0]].columns

In [21]:
smap_dict[basins[0]].columns

Index(['date', 'sm_rootzone_av', 'sm_rootzone_dif', 'sm_rootzone_max',
       'sm_rootzone_min', 'sm_surface_av', 'sm_surface_dif', 'sm_surface_max',
       'sm_surface_min', 'q0_r', 'q0_s'],
      dtype='object')

# Columns to take into account:
3. Hacemos análisis exploratorio  buscando correlaciones entre esos
caudales y las siguientes variables de forma aislada:

   3.a) Del archivo 1 (por cuencas y agregando todos los datos de todas las
cuencas): tav, tmax, tmin, Hrav, Hrmax, Hrmin, wv, wvmax, SolarRad, et0.

   3.b) Del archivo 3: soil_moisture AM, soil_moisture PM (ten en cuenta
que en cada csv hay por cada día una fila con AM y otra con PM, si
prefieres que te lo organice de otra forma para que te sea más fácil
dímelo), promedio de los dos anteriores.

In [22]:
climate_dict_columns_selected = list(set(['Date', 'Year', 'Jdate', 'tav', 'tmax', 'tmin',
       'Hrav', 'Hrmax', 'Hrmin', 'wv', 'wvmax', 'SolarRad', 'et0', 'P', 'ymin', 'yav', 'ymax', 'qmin', 'qav', 'qmax']))

In [23]:
len(climate_dict_columns_selected)

20

In [24]:
for k, v in climate_dict.items():
    climate_dict[k] = climate_dict[k][climate_dict_columns_selected]

In [25]:
climate_dict[basins[0]].columns

Index(['et0', 'Hrav', 'Year', 'Hrmin', 'SolarRad', 'yav', 'tmin', 'wvmax', 'P',
       'qmin', 'Date', 'Jdate', 'qav', 'tav', 'ymax', 'ymin', 'wv', 'Hrmax',
       'tmax', 'qmax'],
      dtype='object')

## Check the data

In [26]:
climate_dict["Anduña"].head()

,et0,Hrav,Year,Hrmin,SolarRad,yav,tmin,wvmax,P,qmin,Date,Jdate,qav,tav,ymax,ymin,wv,Hrmax,tmax,qmax
0,5.1,68.23,2020,50.97,11.91,0.17,4.0,9.07,0.0,0.156,2020-10-01,275,0.17,14.24,0.17,0.16,2.48,84.1,16.0,0.18
1,2.5,86.80,2020,69.30,5.50,0.37,7.0,11.52,30.8,0.156,2020-10-02,276,1.33,9.05,0.61,0.16,3.56,100.0,10.0,3.26
2,2.9,96.20,2020,87.60,3.73,0.59,5.0,6.16,48.4,1.195,2020-10-03,277,3.19,6.49,0.72,0.41,1.25,99.7,9.0,4.80
3,3.9,88.70,2020,75.40,6.32,0.59,4.0,7.20,6.4,1.995,2020-10-04,278,2.99,8.60,0.65,0.51,1.93,100.0,11.0,3.81
4,3.9,85.40,2020,61.78,9.13,0.47,6.0,7.68,1.0,1.345,2020-10-05,279,1.65,9.05,0.57,0.43,1.53,96.9,13.0,2.75

In [27]:
climate_dict["Yanguas"].head()

,et0,Hrav,Year,Hrmin,SolarRad,yav,tmin,wvmax,P,qmin,Date,Jdate,qav,tav,ymax,ymin,wv,Hrmax,tmax,qmax
0,3.03,50.43,2020,39.69,13.98,0.05,11.43,12.05,0.0,0.017,2020-10-01,275,0.017,17.52,0.05,0.05,2.06,66.67,21.10,0.017
1,2.78,65.15,2020,44.10,10.05,0.08,8.16,15.74,21.0,0.017,2020-10-02,276,0.053,12.67,0.12,0.05,3.68,94.90,18.66,0.126
2,2.60,59.74,2020,29.99,11.59,0.07,6.43,8.36,0.0,0.039,2020-10-03,277,0.043,12.07,0.09,0.07,1.77,81.30,19.21,0.061
3,1.75,73.48,2020,58.66,11.00,0.08,8.21,7.01,1.0,0.039,2020-10-04,278,0.046,11.19,0.08,0.07,1.72,89.30,14.39,0.050
4,2.45,64.55,2020,41.25,17.15,0.08,7.73,5.52,0.0,0.050,2020-10-05,279,0.050,13.04,0.08,0.08,1.47,87.40,18.73,0.050

In [28]:
climate_dict["Isuela"].head()

,et0,Hrav,Year,Hrmin,SolarRad,yav,tmin,wvmax,P,qmin,Date,Jdate,qav,tav,ymax,ymin,wv,Hrmax,tmax,qmax
0,2.97,54.93,2020,36.02,15.96,0.09,9.58,5.51,0.0,0.132,2020-10-01,275,0.13,17.93,0.09,0.09,1.40,83.40,24.75,0.13
1,2.20,67.28,2020,45.28,3.68,0.10,7.58,10.00,7.2,0.132,2020-10-02,276,0.15,13.84,0.12,0.09,2.67,93.60,19.59,0.27
2,4.19,51.62,2020,36.64,16.46,0.10,10.72,10.83,0.0,0.160,2020-10-03,277,0.16,14.01,0.10,0.10,4.49,63.69,18.97,0.16
3,2.54,71.00,2020,38.44,10.59,0.10,6.25,9.67,0.0,0.160,2020-10-04,278,0.16,13.03,0.10,0.10,2.18,98.80,20.24,0.16
4,2.17,75.80,2020,42.10,17.73,0.10,3.59,4.39,0.0,0.132,2020-10-05,279,0.16,11.83,0.10,0.09,0.82,99.80,20.22,0.16

In [29]:
physical_dict["Anduña"].head()

,CN_ponderado,CN_DT,n,DT_n,area_cuenca,longitud_total,z_min,z_max,mean_sand,mean_silt,mean_clay,soil_type,ks_st,thetas_st,thetar_st,thau_st,swcfc_st,swcpwp_st,mean_ks,DT_ks,mean_thetas,DT_thetas,mean_thetar,DT_thetar,mean_thau,DT_thau,mean_swcfc,DT_swcfc,mean_swcpwp,DT_swcpwp,lon_min,lon_max,lat_min,lat_max,x_min_25830,x_max_25830,y_min_25830,y_max_25830
0,83.119653,6.103479,0.040012,0.050471,4.716346e+07,12066.232638,796.46698,1725.098022,33.836697,41.072061,25.091414,Loam,10.4,0.43,0.078,960.86766,0.344061,0.115188,8.542988,3.322077,0.425238,0.008518,0.082047,0.00724,971.817394,19.58836,0.352914,0.015838,0.136612,0.038326,-1.05828,-0.95747,42.882873,42.975849,658569.0,666551.0,4749637.0,4760157.0

In [30]:
#humidity_dict["Anduña"].head()

# Preprocessing

In [31]:
climate_dict.keys()

dict_keys(['Anduña', 'Bailin', 'Deza', 'Flamisell', 'Garona', 'Isuela', 'Larraun', 'Nela', 'Oroncillo', 'Rudron', 'Sangüesa', 'Subialde', 'Tiron', 'Ubagua', 'Urrobi', 'Vallfarrera', 'Yanguas', 'Zatoya'])

## Remove erroneous first row in soil moisture files (30/09/2020).

In [32]:
# for k, v in humidity_dict.items():
#     humidity_dict[k] = humidity_dict[k][humidity_dict[k]["dia"]>"2020-09-30"]

## Add Area name to each df

In [33]:
for k, v in climate_dict.items():
    climate_dict[k]["Area_nm"] = k

In [34]:
for k, v in physical_dict.items():
    physical_dict[k]["Area_nm"] = k

In [35]:
# for k, v in humidity_dict.items():
#     humidity_dict[k]["Area_nm"] = k

# # Add Area_nm to SMAP data
# for k, v in smap_dict.items():
#     smap_dict[k]["Area_nm"] = k

In [36]:
climate_dict["Anduña"].head().T

,0,1,2,3,4
et0,5.1,2.5,2.9,3.9,3.9
Hrav,68.23,86.8,96.2,88.7,85.4
Year,2020,2020,2020,2020,2020
Hrmin,50.97,69.3,87.6,75.4,61.78
SolarRad,11.91,5.5,3.73,6.32,9.13
yav,0.17,0.37,0.59,0.59,0.47
tmin,4.0,7.0,5.0,4.0,6.0
wvmax,9.07,11.52,6.16,7.2,7.68
P,0.0,30.8,48.4,6.4,1.0
qmin,0.156,0.156,1.195,1.995,1.345
Date,2020-10-01 00:00:00,2020-10-02 00:00:00,2020-10-03 00:00:00,2020-10-04 00:00:00,2020-10-05 00:00:00
Jdate,275,276,277,278,279
qav,0.17,1.33,3.19,2.99,1.65
tav,14.24,9.05,6.49,8.6,9.05
ymax,0.17,0.61,0.72,0.65,0.57
ymin,0.16,0.16,0.41,0.51,0.43
wv,2.48,3.56,1.25,1.93,1.53
Hrmax,84.1,100.0,99.7,100.0,96.9
tmax,16.0,10.0,9.0,11.0,13.0
qmax,0.18,3.26,4.8,3.81,2.75
Area_nm,Anduña,Anduña,Anduña,Anduña,Anduña

## Check data types

In [37]:
for k, df in climate_dict.items():
    print(f"{k} - Tipos de datos:")
    print(df.dtypes)

Anduña - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Bailin - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Deza - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Flamisell - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Garona - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Isuela - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Larraun - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Nela - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Oroncillo - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Rudron - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Sangüesa - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Subialde - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Tiron - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Ubagua - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Urrobi - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Vallfarrera - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Yanguas - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object
Zatoya - Tipos de datos:
et0                float64
Hrav               float64
Year                 int64
Hrmin              float64
SolarRad           float64
yav                float64
tmin               float64
wvmax              float64
P                  float64
qmin               float64
Date        datetime64[ns]
Jdate                int64
qav                float64
tav                float64
ymax               float64
ymin               float64
wv                 float64
Hrmax              float64
tmax               float64
qmax               float64
Area_nm             object
dtype: object

In [38]:
climate_dict["Anduña"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1826 entries, 0 to 1825
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   et0       1826 non-null   float64
 1   Hrav      1826 non-null   float64
 2   Year      1826 non-null   int64
 3   Hrmin     1826 non-null   float64
 4   SolarRad  1826 non-null   float64
 5   yav       1826 non-null   float64
 6   tmin      1826 non-null   float64
 7   wvmax     1826 non-null   float64
 8   P         1826 non-null   float64
 9   qmin      1826 non-null   float64
 10  Date      1826 non-null   datetime64[ns]
 11  Jdate     1826 non-null   int64
 12  qav       1826 non-null   float64
 13  tav       1826 non-null   float64
 14  ymax      1826 non-null   float64
 15  ymin      1826 non-null   float64
 16  wv        1826 non-null   float64
 17  Hrmax     1826 non-null   float64
 18  tmax      1826 non-null   float64
 19  qmax      1826 non-null   float64
 20  Area_nm   1826 non-null   object
dtypes: datetime64[ns](1), float64(17), int64(2), object(1)
memory usage: 299.7+ KB

In [39]:
climate_dict["Isuela"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1826 entries, 0 to 1825
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   et0       1826 non-null   float64
 1   Hrav      1826 non-null   float64
 2   Year      1826 non-null   int64
 3   Hrmin     1826 non-null   float64
 4   SolarRad  1826 non-null   float64
 5   yav       1826 non-null   float64
 6   tmin      1826 non-null   float64
 7   wvmax     1826 non-null   float64
 8   P         1826 non-null   float64
 9   qmin      1826 non-null   float64
 10  Date      1826 non-null   datetime64[ns]
 11  Jdate     1826 non-null   int64
 12  qav       1826 non-null   float64
 13  tav       1826 non-null   float64
 14  ymax      1826 non-null   float64
 15  ymin      1826 non-null   float64
 16  wv        1826 non-null   float64
 17  Hrmax     1826 non-null   float64
 18  tmax      1826 non-null   float64
 19  qmax      1826 non-null   float64
 20  Area_nm   1826 non-null   object
dtypes: datetime64[ns](1), float64(17), int64(2), object(1)
memory usage: 299.7+ KB

In [40]:
physical_dict["Anduña"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 39 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CN_ponderado    1 non-null      float64
 1   CN_DT           1 non-null      float64
 2   n               1 non-null      float64
 3   DT_n            1 non-null      float64
 4   area_cuenca     1 non-null      float64
 5   longitud_total  1 non-null      float64
 6   z_min           1 non-null      float64
 7   z_max           1 non-null      float64
 8   mean_sand       1 non-null      float64
 9   mean_silt       1 non-null      float64
 10  mean_clay       1 non-null      float64
 11  soil_type       1 non-null      object
 12  ks_st           1 non-null      float64
 13  thetas_st       1 non-null      float64
 14  thetar_st       1 non-null      float64
 15  thau_st         1 non-null      float64
 16  swcfc_st        1 non-null      float64
 17  swcpwp_st       1 non-null      float64
 18  mean_ks         1 non-null      float64
 19  DT_ks           1 non-null      float64
 20  mean_thetas     1 non-null      float64
 21  DT_thetas       1 non-null      float64
 22  mean_thetar     1 non-null      float64
 23  DT_thetar       1 non-null      float64
 24  mean_thau       1 non-null      float64
 25  DT_thau         1 non-null      float64
 26  mean_swcfc      1 non-null      float64
 27  DT_swcfc        1 non-null      float64
 28  mean_swcpwp     1 non-null      float64
 29  DT_swcpwp       1 non-null      float64
 30  lon_min         1 non-null      float64
 31  lon_max         1 non-null      float64
 32  lat_min         1 non-null      float64
 33  lat_max         1 non-null      float64
 34  x_min_25830     1 non-null      float64
 35  x_max_25830     1 non-null      float64
 36  y_min_25830     1 non-null      float64
 37  y_max_25830     1 non-null      float64
 38  Area_nm         1 non-null      object
dtypes: float64(37), object(2)
memory usage: 440.0+ bytes

In [41]:
physical_dict["Isuela"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 39 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CN_ponderado    1 non-null      float64
 1   CN_DT           1 non-null      float64
 2   n               1 non-null      float64
 3   DT_n            1 non-null      float64
 4   area_cuenca     1 non-null      float64
 5   longitud_total  1 non-null      float64
 6   z_min           1 non-null      float64
 7   z_max           1 non-null      float64
 8   mean_sand       1 non-null      float64
 9   mean_silt       1 non-null      float64
 10  mean_clay       1 non-null      float64
 11  soil_type       1 non-null      object
 12  ks_st           1 non-null      float64
 13  thetas_st       1 non-null      float64
 14  thetar_st       1 non-null      float64
 15  thau_st         1 non-null      float64
 16  swcfc_st        1 non-null      float64
 17  swcpwp_st       1 non-null      float64
 18  mean_ks         1 non-null      float64
 19  DT_ks           1 non-null      float64
 20  mean_thetas     1 non-null      float64
 21  DT_thetas       1 non-null      float64
 22  mean_thetar     1 non-null      float64
 23  DT_thetar       1 non-null      float64
 24  mean_thau       1 non-null      float64
 25  DT_thau         1 non-null      float64
 26  mean_swcfc      1 non-null      float64
 27  DT_swcfc        1 non-null      float64
 28  mean_swcpwp     1 non-null      float64
 29  DT_swcpwp       1 non-null      float64
 30  lon_min         1 non-null      float64
 31  lon_max         1 non-null      float64
 32  lat_min         1 non-null      float64
 33  lat_max         1 non-null      float64
 34  x_min_25830     1 non-null      float64
 35  x_max_25830     1 non-null      float64
 36  y_min_25830     1 non-null      float64
 37  y_max_25830     1 non-null      float64
 38  Area_nm         1 non-null      object
dtypes: float64(37), object(2)
memory usage: 440.0+ bytes

In [42]:
# humidity_dict["Urrobi"].info()

## Describe data

In [43]:
climate_dict["Vallfarrera"].describe().T

,count,mean,min,25%,50%,75%,max,std
et0,1826.0,2.283286,0.11,1.03,1.93,3.35,7.3,1.48224
Hrav,1826.0,62.995071,8.0,49.0,65.0,79.0,100.0,20.281295
Year,1826.0,2022.748631,2020.0,2021.25,2023.0,2024.0,2025.0,1.479656
Hrmin,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SolarRad,1826.0,15.853067,0.5,9.4,14.6,22.275,34.3,8.149344
yav,1826.0,0.219238,0.11,0.17,0.19,0.23,0.64,0.081031
tmin,1826.0,2.173384,-16.5,-2.3,1.8,7.0,17.9,6.296751
wvmax,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P,1826.0,1.790252,0.0,0.0,0.0,0.6,61.6,5.051782
qmin,1826.0,1.327198,0.203,0.715,1.043,1.395,8.65,1.01627
Date,1826,2023-04-01 12:00:00,2020-10-01 00:00:00,2021-12-31 06:00:00,2023-04-01 12:00:00,2024-06-30 18:00:00,2025-09-30 00:00:00,NaN
Jdate,1826.0,183.150602,1.0,92.0,183.0,274.75,366.0,105.518435
qav,1826.0,1.488747,0.25,0.8,1.06,1.56,9.78,1.19634
tav,1826.0,5.759365,-12.9,0.8,5.4,10.775,22.0,6.652219
ymax,1826.0,0.232273,0.11,0.17,0.2,0.25,0.79,0.094974
ymin,1826.0,0.207777,0.1,0.16,0.19,0.22,0.6,0.07285
wv,1826.0,1.166703,0.0,0.7,1.0,1.475,5.0,0.663819
Hrmax,1826.0,85.786966,17.0,77.0,94.0,100.0,100.0,18.375596
tmax,1826.0,10.077382,-11.2,4.8,9.7,15.475,27.3,7.26694
qmax,1826.0,1.689355,0.28,0.82,1.15,1.76,13.92,1.502138

In [44]:
physical_dict["Urrobi"].describe().T

,count,mean,std,min,25%,50%,75%,max
CN_ponderado,1.0,8.360682e+01,NaN,8.360682e+01,8.360682e+01,8.360682e+01,8.360682e+01,8.360682e+01
CN_DT,1.0,6.389916e+00,NaN,6.389916e+00,6.389916e+00,6.389916e+00,6.389916e+00,6.389916e+00
n,1.0,4.020930e-02,NaN,4.020930e-02,4.020930e-02,4.020930e-02,4.020930e-02,4.020930e-02
DT_n,1.0,5.547753e-02,NaN,5.547753e-02,5.547753e-02,5.547753e-02,5.547753e-02,5.547753e-02
area_cuenca,1.0,4.846226e+07,NaN,4.846226e+07,4.846226e+07,4.846226e+07,4.846226e+07,4.846226e+07
longitud_total,1.0,1.161159e+04,NaN,1.161159e+04,1.161159e+04,1.161159e+04,1.161159e+04,1.161159e+04
z_min,1.0,8.399360e+02,NaN,8.399360e+02,8.399360e+02,8.399360e+02,8.399360e+02,8.399360e+02
z_max,1.0,1.528596e+03,NaN,1.528596e+03,1.528596e+03,1.528596e+03,1.528596e+03,1.528596e+03
mean_sand,1.0,2.806113e+01,NaN,2.806113e+01,2.806113e+01,2.806113e+01,2.806113e+01,2.806113e+01
mean_silt,1.0,4.512178e+01,NaN,4.512178e+01,4.512178e+01,4.512178e+01,4.512178e+01,4.512178e+01
mean_clay,1.0,2.681802e+01,NaN,2.681802e+01,2.681802e+01,2.681802e+01,2.681802e+01,2.681802e+01
ks_st,1.0,1.040000e+01,NaN,1.040000e+01,1.040000e+01,1.040000e+01,1.040000e+01,1.040000e+01
thetas_st,1.0,4.300000e-01,NaN,4.300000e-01,4.300000e-01,4.300000e-01,4.300000e-01,4.300000e-01
thetar_st,1.0,7.800000e-02,NaN,7.800000e-02,7.800000e-02,7.800000e-02,7.800000e-02,7.800000e-02
thau_st,1.0,9.608677e+02,NaN,9.608677e+02,9.608677e+02,9.608677e+02,9.608677e+02,9.608677e+02
swcfc_st,1.0,3.440607e-01,NaN,3.440607e-01,3.440607e-01,3.440607e-01,3.440607e-01,3.440607e-01
swcpwp_st,1.0,1.151879e-01,NaN,1.151879e-01,1.151879e-01,1.151879e-01,1.151879e-01,1.151879e-01
mean_ks,1.0,6.563319e+00,NaN,6.563319e+00,6.563319e+00,6.563319e+00,6.563319e+00,6.563319e+00
DT_ks,1.0,3.813135e+00,NaN,3.813135e+00,3.813135e+00,3.813135e+00,3.813135e+00,3.813135e+00
mean_thetas,1.0,4.235401e-01,NaN,4.235401e-01,4.235401e-01,4.235401e-01,4.235401e-01,4.235401e-01
DT_thetas,1.0,1.247167e-02,NaN,1.247167e-02,1.247167e-02,1.247167e-02,1.247167e-02,1.247167e-02
mean_thetar,1.0,8.417335e-02,NaN,8.417335e-02,8.417335e-02,8.417335e-02,8.417335e-02,8.417335e-02
DT_thetar,1.0,9.592409e-03,NaN,9.592409e-03,9.592409e-03,9.592409e-03,9.592409e-03,9.592409e-03
mean_thau,1.0,9.800800e+02,NaN,9.800800e+02,9.800800e+02,9.800800e+02,9.800800e+02,9.800800e+02
DT_thau,1.0,2.861300e+01,NaN,2.861300e+01,2.861300e+01,2.861300e+01,2.861300e+01,2.861300e+01
mean_swcfc,1.0,3.657192e-01,NaN,3.657192e-01,3.657192e-01,3.657192e-01,3.657192e-01,3.657192e-01
DT_swcfc,1.0,2.266744e-02,NaN,2.266744e-02,2.266744e-02,2.266744e-02,2.266744e-02,2.266744e-02
mean_swcpwp,1.0,1.581998e-01,NaN,1.581998e-01,1.581998e-01,1.581998e-01,1.581998e-01,1.581998e-01
DT_swcpwp,1.0,4.476893e-02,NaN,4.476893e-02,4.476893e-02,4.476893e-02,4.476893e-02,4.476893e-02
lon_min,1.0,-1.390179e+00,NaN,-1.390179e+00,-1.390179e+00,-1.390179e+00,-1.390179e+00,-1.390179e+00
lon_max,1.0,-1.279160e+00,NaN,-1.279160e+00,-1.279160e+00,-1.279160e+00,-1.279160e+00,-1.279160e+00
lat_min,1.0,4.293706e+01,NaN,4.293706e+01,4.293706e+01,4.293706e+01,4.293706e+01,4.293706e+01
lat_max,1.0,4.302870e+01,NaN,4.302870e+01,4.302870e+01,4.302870e+01,4.302870e+01,4.302870e+01
x_min_25830,1.0,6.313490e+05,NaN,6.313490e+05,6.313490e+05,6.313490e+05,6.313490e+05,6.313490e+05
x_max_25830,1.0,6.401990e+05,NaN,6.401990e+05,6.401990e+05,6.401990e+05,6.401990e+05,6.401990e+05
y_min_25830,1.0,4.755083e+06,NaN,4.755083e+06,4.755083e+06,4.755083e+06,4.755083e+06,4.755083e+06
y_max_25830,1.0,4.765439e+06,NaN,4.765439e+06,4.765439e+06,4.765439e+06,4.765439e+06,4.765439e+06

In [45]:
# humidity_dict["Urrobi"].describe().T

# Boxplots

In [46]:
os.makedirs("0-boxplots", exist_ok=True)

In [47]:
# # Ejemplo: boxplots para variables de caudal en una cuenca
# variables = ["qmin", "qav", "qmax"]

# for k, v in humidity_dict.items():
#     print("\n", k)
# # Suponiendo que tienes un DataFrame para una cuenca, por ejemplo:
#     df = climate_dict[k]
    
    
#     plt.figure(figsize=(12, 6))
#     for i, var in enumerate(variables, 1):
#         plt.subplot(1, 3, i)
#         sns.boxplot(y=df[var], color="skyblue", fliersize=3)  # fliersize controla los outliers
#         plt.title(f"Boxplot de {var}")
#     plt.tight_layout()
#     plt.savefig(f"0-boxplots/{k}_boxplots.png", dpi=300)
#     plt.show()

## Check nulls in columns

In [48]:
for k, v in climate_dict.items():
    print("\n", k)
    #print(climate_dict[k].isnull().sum())
    print(climate_dict[k].isnull().mean().round(3) * 100) # % of null values

 Anduña
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Bailin
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Deza
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Flamisell
et0           0.0
Hrav          0.0
Year          0.0
Hrmin       100.0
SolarRad      0.0
yav           0.0
tmin          0.0
wvmax       100.0
P             0.0
qmin          0.0
Date          0.0
Jdate         0.0
qav           0.0
tav           0.0
ymax          0.0
ymin          0.0
wv            0.0
Hrmax         0.0
tmax          0.0
qmax          0.0
Area_nm       0.0
dtype: float64

 Garona
et0           0.0
Hrav          0.0
Year          0.0
Hrmin       100.0
SolarRad      0.0
yav           0.0
tmin          0.0
wvmax       100.0
P             0.0
qmin          0.0
Date          0.0
Jdate         0.0
qav           0.0
tav           0.0
ymax          0.0
ymin          0.0
wv            0.0
Hrmax         0.0
tmax          0.0
qmax          0.0
Area_nm       0.0
dtype: float64

 Isuela
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Larraun
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Nela
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Oroncillo
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Rudron
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Sangüesa
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Subialde
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Tiron
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Ubagua
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Urrobi
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Vallfarrera
et0           0.0
Hrav          0.0
Year          0.0
Hrmin       100.0
SolarRad      0.0
yav           0.0
tmin          0.0
wvmax       100.0
P             0.0
qmin          0.0
Date          0.0
Jdate         0.0
qav           0.0
tav           0.0
ymax          0.0
ymin          0.0
wv            0.0
Hrmax         0.0
tmax          0.0
qmax          0.0
Area_nm       0.0
dtype: float64

 Yanguas
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

 Zatoya
et0         0.0
Hrav        0.0
Year        0.0
Hrmin       0.0
SolarRad    0.0
yav         0.0
tmin        0.0
wvmax       0.0
P           0.0
qmin        0.0
Date        0.0
Jdate       0.0
qav         0.0
tav         0.0
ymax        0.0
ymin        0.0
wv          0.0
Hrmax       0.0
tmax        0.0
qmax        0.0
Area_nm     0.0
dtype: float64

In [49]:
for k, v in physical_dict.items():
    print("\n", k)
    #print(physical_dict[k].isnull().sum())
    print(physical_dict[k].isnull().mean().round(3) * 100) # % of null values

 Anduña
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Bailin
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Deza
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Flamisell
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Garona
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Isuela
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Larraun
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Nela
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Oroncillo
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Rudron
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Sangüesa
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Subialde
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Tiron
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Ubagua
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Urrobi
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Vallfarrera
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Yanguas
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

 Zatoya
CN_ponderado      0.0
CN_DT             0.0
n                 0.0
DT_n              0.0
area_cuenca       0.0
longitud_total    0.0
z_min             0.0
z_max             0.0
mean_sand         0.0
mean_silt         0.0
mean_clay         0.0
soil_type         0.0
ks_st             0.0
thetas_st         0.0
thetar_st         0.0
thau_st           0.0
swcfc_st          0.0
swcpwp_st         0.0
mean_ks           0.0
DT_ks             0.0
mean_thetas       0.0
DT_thetas         0.0
mean_thetar       0.0
DT_thetar         0.0
mean_thau         0.0
DT_thau           0.0
mean_swcfc        0.0
DT_swcfc          0.0
mean_swcpwp       0.0
DT_swcpwp         0.0
lon_min           0.0
lon_max           0.0
lat_min           0.0
lat_max           0.0
x_min_25830       0.0
x_max_25830       0.0
y_min_25830       0.0
y_max_25830       0.0
Area_nm           0.0
dtype: float64

In [50]:
# for k, v in humidity_dict.items():
#     print("\n", k)
#     #print(humidity_dict[k].isnull().sum())
#     print(humidity_dict[k].isnull().mean().round(3) * 100) # % of null values

In [51]:
for k, v in smap_dict.items():
    print("\n", k)
    #print(smap_dict[k].isnull().sum())
    print(smap_dict[k].isnull().mean().round(3) * 100) # % of null values

 Anduña
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Bailin
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Deza
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Flamisell
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Garona
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Isuela
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Larraun
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Nela
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Oroncillo
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Rudron
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Sangüesa
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Subialde
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Tiron
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Ubagua
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Urrobi
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Vallfarrera
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Yanguas
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

 Zatoya
date               0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
dtype: float64

# Drop columns with 100% of null values

In [52]:
for k, v in climate_dict.items():
    climate_dict[k] = climate_dict[k].dropna(axis=1, how="all")

In [53]:
# 3. Comprobar si todas las columnas del DataFrame están en la lista seleccionada
def check_columns(my_dict, columns_list):
    for k, v in my_dict.items():
        if (set(my_dict[k].columns)- {"Area_nm"}).issubset(columns_list):
            print(f"{k}:", f"\t✅ Todas las columnas del DataFrame están presentes")
        else:
            print("⚠️ Hay columnas que no están en my_dict:")
            print(k, (set(my_dict[k].columns)- {'Area_nm'}) - set(columns_list))

In [54]:
check_columns(climate_dict, climate_dict_columns_selected)

Anduña: 	✅ Todas las columnas del DataFrame están presentes
Bailin: 	✅ Todas las columnas del DataFrame están presentes
Deza: 	✅ Todas las columnas del DataFrame están presentes
Flamisell: 	✅ Todas las columnas del DataFrame están presentes
Garona: 	✅ Todas las columnas del DataFrame están presentes
Isuela: 	✅ Todas las columnas del DataFrame están presentes
Larraun: 	✅ Todas las columnas del DataFrame están presentes
Nela: 	✅ Todas las columnas del DataFrame están presentes
Oroncillo: 	✅ Todas las columnas del DataFrame están presentes
Rudron: 	✅ Todas las columnas del DataFrame están presentes
Sangüesa: 	✅ Todas las columnas del DataFrame están presentes
Subialde: 	✅ Todas las columnas del DataFrame están presentes
Tiron: 	✅ Todas las columnas del DataFrame están presentes
Ubagua: 	✅ Todas las columnas del DataFrame están presentes
Urrobi: 	✅ Todas las columnas del DataFrame están presentes
Vallfarrera: 	✅ Todas las columnas del DataFrame están presentes
Yanguas: 	✅ Todas las columnas del DataFrame están presentes
Zatoya: 	✅ Todas las columnas del DataFrame están presentes

## Eliminación de Outliers

**Estrategia de detección y eliminación de outliers:**

Para garantizar la calidad de los datos y evitar que valores atípicos afecten el análisis y modelado predictivo,
aplicamos el **método IQR (Interquartile Range)**:

### Método IQR (Rango Intercuartílico)

1. **Cálculo de cuartiles:**
   - Q1 (primer cuartil): percentil 25
   - Q3 (tercer cuartil): percentil 75
   - IQR = Q3 - Q1

2. **Definición de límites:**
   - Límite inferior: Q1 - 1.5 × IQR
   - Límite superior: Q3 + 1.5 × IQR

3. **Tratamiento de outliers:**
   - Los valores fuera de estos límites se reemplazan por `NaN`
   - Esto preserva la integridad de los datos (valores válidos dentro del rango se mantienen)
   - Los valores NaN permiten análisis posteriores sin introducir sesgos artificiales

### Variables analizadas

La función se aplica a las siguientes variables climáticas continuas:
- **Temperatura:** `tav`, `tmax`, `tmin`
- **Humedad relativa:** `Hrav`, `Hrmax`, `Hrmin`
- **Viento:** `wv`, `wvmax`
- **Radiación solar:** `SolarRad`
- **Evapotranspiración:** `et0`
- **Precipitación:** `p`
- **Caudales:** `qmax`, `qav`, `qmin`

**Nota:** Las variables temporales (`Jdate`, `Year`, `Month`, `Day`) no se procesan ya que no son métricas continuas susceptibles a outliers.

In [55]:
# def remove_outliers_iqr(data_dict, variables=None, multiplier=1.5):
#     """
#     Elimina outliers de un diccionario de DataFrames usando el método IQR.
    
#     Parameters:
#     -----------
#     data_dict : dict
#         Diccionario con DataFrames (ej: climate_dict)
#     variables : list, optional
#         Lista de variables a procesar. Si None, se procesan todas las columnas numéricas
#     multiplier : float, default=1.5
#         Multiplicador del IQR para definir los límites (1.5 es el estándar)
    
#     Returns:
#     --------
#     dict
#         Diccionario con DataFrames sin outliers
#     dict
#         Diccionario con estadísticas de outliers eliminados por cuenca
#     """
    
#     outliers_stats = {}
    
#     for basin_name, df in data_dict.items():
#         basin_stats = {}
        
#         # Si no se especifican variables, usar todas las numéricas
#         cols_to_process = variables if variables else df.select_dtypes(include=[np.number]).columns.tolist()
        
#         for col in cols_to_process:
#             if col not in df.columns:
#                 continue
                
#             # Calcular IQR
#             Q1 = df[col].quantile(0.25)
#             Q3 = df[col].quantile(0.75)
#             IQR = Q3 - Q1
            
#             # Definir límites
#             lower_bound = Q1 - multiplier * IQR
#             upper_bound = Q3 + multiplier * IQR
            
#             # Identificar outliers
#             outlier_mask = (df[col] < lower_bound) | (df[col] > upper_bound)
#             n_outliers = outlier_mask.sum()
            
#             # Reemplazar outliers con NaN
#             if n_outliers > 0:
#                 df.loc[outlier_mask, col] = np.nan
#                 basin_stats[col] = {
#                     'n_outliers': int(n_outliers),
#                     'lower_bound': float(lower_bound),
#                     'upper_bound': float(upper_bound),
#                     'Q1': float(Q1),
#                     'Q3': float(Q3),
#                     'IQR': float(IQR)
#                 }
        
#         if basin_stats:
#             outliers_stats[basin_name] = basin_stats
    
#     return data_dict, outliers_stats

In [56]:
# # Variables climáticas a procesar (excluyendo variables temporales)
# climate_vars_to_clean = [
#     'tav', 'tmax', 'tmin',           # Temperatura
#     'Hrav', 'Hrmax', 'Hrmin',        # Humedad relativa
#     'wv', 'wvmax',                   # Viento
#     'SolarRad',                      # Radiación solar
#     'et0',                           # Evapotranspiración
#     'p',                             # Precipitación
#     'qmax', 'qav', 'qmin'            # Caudales
# ]

# print("Aplicando eliminación de outliers (método IQR)...\n")

# # Aplicar eliminación de outliers
# climate_dict, outliers_stats = remove_outliers_iqr(climate_dict, climate_vars_to_clean)

# # Mostrar resumen
# if outliers_stats:
#     print("📊 Resumen de outliers eliminados por cuenca:\n")
    
#     for basin, stats in sorted(outliers_stats.items()):
#         total_outliers = sum(var_stats['n_outliers'] for var_stats in stats.values())
#         print(f"  {basin}: {total_outliers} outliers totales")
        
#         # Mostrar detalles de las 3 variables con más outliers
#         sorted_vars = sorted(stats.items(), key=lambda x: x[1]['n_outliers'], reverse=True)[:3]
#         for var, var_stats in sorted_vars:
#             print(f"    - {var}: {var_stats['n_outliers']} outliers "
#                   f"(rango válido: {var_stats['lower_bound']:.2f} - {var_stats['upper_bound']:.2f})")
#         print()
# else:
#     print("✓ No se encontraron outliers en los datos climáticos")

# print("\n✅ Eliminación de outliers completada exitosamente")

In [57]:
for k, v in physical_dict.items():
    physical_dict[k] = physical_dict[k].dropna(axis=1, how="all")

In [58]:
# for k, v in humidity_dict.items():
#     humidity_dict[k] = humidity_dict[k].dropna(axis=1, how="all")

In [59]:
for k, v in smap_dict.items():
    smap_dict[k] = smap_dict[k].dropna(axis=1, how="all")

## Drop rows with null values

In [60]:
for k, v in climate_dict.items():
    climate_dict[k] = climate_dict[k].dropna(axis=0)

## Data Cleaning Transformations

**Important corrections based on data quality review (Sergi, 2025-12-09):**

1. **Bailín discharge units correction**: Values are in incorrect units (L/s instead of m³/s)
2. **Anomalous discharge values**: Some basins (especially Sangüesa) have erroneous values ~10^9 m³/s

These transformations are applied before saving the clean data.

In [61]:
# ===============================================
# DATA CLEANING TRANSFORMATIONS
# ===============================================

print("Aplicando transformaciones de limpieza...")

# 1. TRANSFORMAR UNIDADES DE CAUDAL EN BAILÍN
# Los valores de Bailín están en unidades incorrectas (probablemente L/s en lugar de m³/s)
# Se dividen por 1000 para corregir
if "Bailin" in climate_dict:
    print("\n1. Corrigiendo unidades de caudal en Bailín (dividiendo por 1000)...")
    
    # Guardar valores originales para comparación
    bailin_qmax_before = climate_dict["Bailin"]["qmax"].describe()
    
    climate_dict["Bailin"]["qmax"] = climate_dict["Bailin"]["qmax"] / 1000
    climate_dict["Bailin"]["qav"] = climate_dict["Bailin"]["qav"] / 1000
    climate_dict["Bailin"]["qmin"] = climate_dict["Bailin"]["qmin"] / 1000
    
    print(f"   ✓ Bailín qmax range: {climate_dict['Bailin']['qmax'].min():.4f} - {climate_dict['Bailin']['qmax'].max():.4f} m³/s")
    print(f"   ✓ Bailín qav range: {climate_dict['Bailin']['qav'].min():.4f} - {climate_dict['Bailin']['qav'].max():.4f} m³/s")
    print(f"   ✓ Bailín qmin range: {climate_dict['Bailin']['qmin'].min():.4f} - {climate_dict['Bailin']['qmin'].max():.4f} m³/s")

# 2. ELIMINAR VALORES ANÓMALOS DE CAUDAL
# Hay valores del orden de 10^9 que son errores de medición
# Se reemplazan con NaN todos los valores de qmax, qav, qmin > 1000 m³/s

print("\n2. Eliminando valores anómalos (>1000 m³/s)...")

# Contador de valores anómalos por cuenca
anomalies_count = {}

for basin in climate_dict.keys():
    count = 0
    
    # qmax
    mask_qmax = climate_dict[basin]["qmax"] > 1000
    if mask_qmax.any():
        count += mask_qmax.sum()
        climate_dict[basin].loc[mask_qmax, "qmax"] = np.nan
    
    # qav
    mask_qav = climate_dict[basin]["qav"] > 1000
    if mask_qav.any():
        count += mask_qav.sum()
        climate_dict[basin].loc[mask_qav, "qav"] = np.nan
    
    # qmin
    mask_qmin = climate_dict[basin]["qmin"] > 1000
    if mask_qmin.any():
        count += mask_qmin.sum()
        climate_dict[basin].loc[mask_qmin, "qmin"] = np.nan
    
    if count > 0:
        anomalies_count[basin] = count

# Mostrar resumen de valores anómalos eliminados
if anomalies_count:
    print("   Valores anómalos (>1000 m³/s) reemplazados con NaN:")
    for basin, count in anomalies_count.items():
        print(f"   ✓ {basin}: {count} valores anómalos detectados y eliminados")
else:
    print("   ✓ No se encontraron valores anómalos >1000 m³/s")

print("\n✅ Transformaciones de limpieza completadas exitosamente")

Aplicando transformaciones de limpieza...

1. Corrigiendo unidades de caudal en Bailín (dividiendo por 1000)...
   ✓ Bailín qmax range: 0.0000 - 0.9052 m³/s
   ✓ Bailín qav range: 0.0000 - 0.3037 m³/s
   ✓ Bailín qmin range: 0.0000 - 0.2010 m³/s

2. Eliminando valores anómalos (>1000 m³/s)...
   Valores anómalos (>1000 m³/s) reemplazados con NaN:
   ✓ Sangüesa: 114 valores anómalos detectados y eliminados

✅ Transformaciones de limpieza completadas exitosamente

In [62]:
# Verificar rangos después de limpieza en las cuencas más afectadas
print("Verificación de rangos después de limpieza:\n")

basins_to_check = ["Bailin", "Sangüesa", "Anduña", "Garona"]

for basin in basins_to_check:
    if basin in climate_dict:
        print(f"{basin}:")
        print(f"  qmax: {climate_dict[basin]['qmax'].min():.4f} - {climate_dict[basin]['qmax'].max():.4f} m³/s (mean: {climate_dict[basin]['qmax'].mean():.4f})")
        print(f"  qav:  {climate_dict[basin]['qav'].min():.4f} - {climate_dict[basin]['qav'].max():.4f} m³/s (mean: {climate_dict[basin]['qav'].mean():.4f})")
        print(f"  qmin: {climate_dict[basin]['qmin'].min():.4f} - {climate_dict[basin]['qmin'].max():.4f} m³/s (mean: {climate_dict[basin]['qmin'].mean():.4f})")
        print()

Verificación de rangos después de limpieza:

Bailin:
  qmax: 0.0000 - 0.9052 m³/s (mean: 0.0464)
  qav:  0.0000 - 0.3037 m³/s (mean: 0.0201)
  qmin: 0.0000 - 0.2010 m³/s (mean: 0.0134)

Sangüesa:
  qmax: 0.0080 - 41.8400 m³/s (mean: 1.0619)
  qav:  0.0080 - 21.1000 m³/s (mean: 0.6661)
  qmin: 0.0060 - 7.9000 m³/s (mean: 0.5212)

Anduña:
  qmax: 0.0400 - 46.7700 m³/s (mean: 1.9661)
  qav:  0.0400 - 32.9100 m³/s (mean: 1.3239)
  qmin: 0.0200 - 23.9000 m³/s (mean: 0.9362)

Garona:
  qmax: 1.1800 - 69.2400 m³/s (mean: 11.5519)
  qav:  1.0000 - 53.5800 m³/s (mean: 7.0179)
  qmin: 1.0000 - 44.5800 m³/s (mean: 4.5351)

In [63]:
check_columns(climate_dict, climate_dict_columns_selected)

Anduña: 	✅ Todas las columnas del DataFrame están presentes
Bailin: 	✅ Todas las columnas del DataFrame están presentes
Deza: 	✅ Todas las columnas del DataFrame están presentes
Flamisell: 	✅ Todas las columnas del DataFrame están presentes
Garona: 	✅ Todas las columnas del DataFrame están presentes
Isuela: 	✅ Todas las columnas del DataFrame están presentes
Larraun: 	✅ Todas las columnas del DataFrame están presentes
Nela: 	✅ Todas las columnas del DataFrame están presentes
Oroncillo: 	✅ Todas las columnas del DataFrame están presentes
Rudron: 	✅ Todas las columnas del DataFrame están presentes
Sangüesa: 	✅ Todas las columnas del DataFrame están presentes
Subialde: 	✅ Todas las columnas del DataFrame están presentes
Tiron: 	✅ Todas las columnas del DataFrame están presentes
Ubagua: 	✅ Todas las columnas del DataFrame están presentes
Urrobi: 	✅ Todas las columnas del DataFrame están presentes
Vallfarrera: 	✅ Todas las columnas del DataFrame están presentes
Yanguas: 	✅ Todas las columnas del DataFrame están presentes
Zatoya: 	✅ Todas las columnas del DataFrame están presentes

In [64]:
for k, v in physical_dict.items():
    physical_dict[k] = physical_dict[k].dropna(axis=0)

In [65]:
# for k, v in humidity_dict.items():
#     humidity_dict[k] = humidity_dict[k].dropna(axis=0)

In [66]:
for k, v in smap_dict.items():
    smap_dict[k] = smap_dict[k].dropna(axis=0)

# Save clean data

## Save climate_dict sorted columns

In [67]:
base_path = "../../data/clean/basins/climate/"

In [68]:
for k, v_df in climate_dict.items():
    # v_df.reindex(columns=sorted(list(v_df.columns))).to_json(f"{base_path}{k}-without-outliers.json", orient="records", indent=4) # WHIHTOUT OUTLIERS
    v_df.reindex(columns=sorted(list(v_df.columns))).to_json(f"{base_path}{k}-with-outliers.json", orient="records", indent=4) # WHITH OUTLIERS

In [69]:
# Reconstruir el diccionario
climate_dict_restored = {}

for filename in os.listdir(base_path):
    if filename.endswith("with-outliers.json"):
        # El nombre del archivo sin extensión
        basin_name = os.path.splitext(filename)[0]
        
        # Leer el JSON como DataFrame
        df = pd.read_json(os.path.join(base_path, filename), orient="records")
        
        climate_dict_restored[basin_name] = df

# Ahora climate_dict_restored tiene la misma estructura que el original
print(climate_dict_restored.keys())

dict_keys(['Tiron-with-outliers', 'Oroncillo-with-outliers', 'Rudron-with-outliers', 'Larraun-with-outliers', 'Zatoya-with-outliers', 'Flamisell-with-outliers', 'Vallfarrera-with-outliers', 'Yanguas-with-outliers', 'Garona-with-outliers', 'Urrobi-with-outliers', 'Anduña-with-outliers', 'Bailin-with-outliers', 'Nela-with-outliers', 'Deza-with-outliers', 'Ubagua-with-outliers', 'Isuela-with-outliers', 'Subialde-with-outliers', 'Sangüesa-with-outliers'])

In [70]:
climate_dict_restored['Larraun-with-outliers'].head()

,Area_nm,Date,Hrav,Hrmax,Hrmin,Jdate,P,SolarRad,Year,et0,qav,qmax,qmin,tav,tmax,tmin,wv,wvmax,yav,ymax,ymin
0,Larraun,2020-10-01,79.18,96.0,50.69,275,0.8,8.95,2020,1.61,0.0,0.378,0.332,13.90,18.52,9.69,0.85,4.41,0.70,0.71,0.69
1,Larraun,2020-10-02,67.92,93.7,52.07,276,28.8,8.06,2020,1.76,8.0,20.532,0.332,11.76,17.38,8.78,1.58,6.92,1.03,1.41,0.69
2,Larraun,2020-10-03,79.37,95.0,64.30,277,22.4,4.09,2020,1.04,19.0,31.604,3.719,9.76,14.05,6.84,0.94,5.35,1.34,1.66,0.92
3,Larraun,2020-10-04,75.25,97.0,50.76,278,4.8,8.23,2020,1.52,7.0,19.212,4.053,10.94,16.39,6.64,1.10,7.28,1.03,1.38,0.94
4,Larraun,2020-10-05,76.75,96.0,43.80,279,3.6,7.78,2020,1.31,3.0,3.995,1.729,11.68,17.65,8.20,0.47,2.22,0.87,0.94,0.84

In [71]:
climate_dict_restored["Tiron-with-outliers"].head()

,Area_nm,Date,Hrav,Hrmax,Hrmin,Jdate,P,SolarRad,Year,et0,qav,qmax,qmin,tav,tmax,tmin,wv,wvmax,yav,ymax,ymin
0,Tiron,2020-10-01,66.94,100.0,42.63,275,0.0,8.76,2020,2.33,0.07,0.07,0.072,15.40,20.33,9.65,2.22,7.27,0.06,0.06,0.06
1,Tiron,2020-10-02,72.90,100.0,50.36,276,8.8,12.80,2020,2.49,0.09,0.10,0.072,10.71,15.46,7.53,4.82,12.54,0.06,0.07,0.06
2,Tiron,2020-10-03,72.40,88.6,56.63,277,0.0,7.40,2020,1.89,0.08,0.10,0.072,10.25,15.21,6.92,2.79,9.16,0.06,0.07,0.06
3,Tiron,2020-10-04,76.70,100.0,58.44,278,0.4,8.17,2020,1.67,0.07,0.07,0.072,10.78,14.91,6.65,2.60,9.85,0.06,0.06,0.06
4,Tiron,2020-10-05,71.90,95.7,38.29,279,0.0,15.46,2020,2.30,0.08,0.10,0.072,12.30,19.19,6.72,1.37,6.15,0.06,0.07,0.06

## Save physical_dict sorted columns

In [72]:
base_path = "../../data/clean/basins/physical/"

In [73]:
for k, v_df in physical_dict.items():
    # v_df.reindex(columns=sorted(list(v_df.columns))).to_json(f"{base_path}{k}-without-outliers.json", orient="records", indent=4) # WHITHOUT OUTLIERS
    v_df.reindex(columns=sorted(list(v_df.columns))).to_json(f"{base_path}{k}-with-outliers.json", orient="records", indent=4) # WHITH OUTLIERS

In [74]:
# Reconstruir el diccionario
physical_dict_restored = {}

for filename in os.listdir(base_path):
    if filename.endswith(".json"):
        # El nombre del archivo sin extensión
        basin_name = os.path.splitext(filename)[0]
        
        # Leer el JSON como DataFrame
        df = pd.read_json(os.path.join(base_path, filename), orient="records")
        
        physical_dict_restored[basin_name] = df

# Ahora climate_dict_restored tiene la misma estructura que el original
print(physical_dict_restored.keys())

dict_keys(['Ubagua-without-outliers', 'Tiron-without-outliers', 'Subialde-without-outliers', 'Oroncillo-without-outliers', 'Tiron-with-outliers', 'Deza', 'Oroncillo-with-outliers', 'Rudron-with-outliers', 'Larraun-with-outliers', 'Larraun', 'Flamisell', 'Anduña-without-outliers', 'Zidacos', 'Subialde', 'Isuela-without-outliers', 'Zatoya', 'Zatoya-with-outliers', 'Yanguas', 'Flamisell-with-outliers', 'Vallfarrera', 'Yanguas-without-outliers', 'Deza-without-outliers', 'Vallfarrera-with-outliers', 'Anduña', 'Nela-without-outliers', 'Zatoya-without-outliers', 'Yanguas-with-outliers', 'Garona-with-outliers', 'Garona-without-outliers', 'Flamisell-without-outliers', 'Vallfarrera-without-outliers', 'Rudron-without-outliers', 'Bailin-without-outliers', 'Urrobi-with-outliers', 'Sangüesa-without-outliers', 'Isuela', 'Urrobi', 'Bailin', 'Oroncillo', 'Anduña-with-outliers', 'Trueba', 'Sangüesa', 'Tiron', 'Bailin-with-outliers', 'Rudron', 'Nela-with-outliers', 'Deza-with-outliers', 'Ubagua-with-outliers', 'Isuela-with-outliers', 'Nela', 'Subialde-with-outliers', 'Garona', 'Sangüesa-with-outliers', 'Ubagua', 'Urrobi-without-outliers', 'Larraun-without-outliers'])

In [75]:
physical_dict_restored['Larraun-without-outliers'].head()

,Area_nm,CN_DT,CN_ponderado,DT_ks,DT_n,DT_swcfc,DT_swcpwp,DT_thau,DT_thetar,DT_thetas,area_cuenca,ks_st,lat_max,lat_min,lon_max,lon_min,longitud_total,mean_clay,mean_ks,mean_sand,mean_silt,mean_swcfc,mean_swcpwp,mean_thau,mean_thetar,mean_thetas,n,soil_type,swcfc_st,swcpwp_st,thau_st,thetar_st,thetas_st,x_max_25830,x_min_25830,y_max_25830,y_min_25830,z_max,z_min
0,Larraun,6.490579,82.408595,3.414181,0.051786,0.025933,0.054567,78.451315,0.007337,0.011107,5.825444e+06,2.6,42.989489,42.951597,-1.894037,-1.92247,3067.464024,30.614473,3.373324,22.445592,46.950326,0.388267,0.210787,935.731611,0.088842,0.422135,0.039422,Loam,0.381248,0.205174,1006.859753,0.095,0.41,590161.0,587897.0,4760241,4756003,1121.973022,560.38501

## Save humidity_dict sorted columns

In [76]:
# base_path = "../../data/clean/basins/humidity/"

In [77]:
# for k, v_df in humidity_dict.items():
#     v_df.reindex(columns=sorted(list(v_df.columns))).to_json(f"{base_path}{k}-without-outliers.json", orient="records", indent=4)

In [78]:
# # Reconstruir el diccionario
# humidity_dict_restored = {}

# for filename in os.listdir(base_path):
#     if filename.endswith(".json"):
#         # El nombre del archivo sin extensión
#         basin_name = os.path.splitext(filename)[0]
        
#         # Leer el JSON como DataFrame
#         df = pd.read_json(os.path.join(base_path, filename), orient="records")
        
#         humidity_dict_restored[basin_name] = df

# # Ahora climate_dict_restored tiene la misma estructura que el original
# print(humidity_dict_restored.keys())

In [79]:
# humidity_dict_restored['Larraun'].head()

# Merge all data

## 🔍 DEBUG: Verificación antes del merge

In [80]:
# DEBUG 1: Verificar intersección de keys
climate_keys = set(climate_dict.keys())
physical_keys = set(physical_dict.keys())
# humidity_keys = set(humidity_dict.keys())
smap_keys = set(smap_dict.keys())
print(f"📊 Número de keys por dictionary:")
print(f"  - climate_dict:  {len(climate_keys)}")
print(f"  - physical_dict: {len(physical_keys)}")
# print(f"  - humidity_dict: {len(humidity_keys)}")
print(f"  - smap_dict:     {len(smap_keys)}")
common_keys = climate_keys & physical_keys & smap_keys# & humidity_keys 
print(f"\n✅ Keys comunes a los 4 dictionaries: {len(common_keys)}")
print(f"   {sorted(common_keys)}")
if len(common_keys) == 0:    
    print("\n⚠️  PROBLEMA: No hay keys comunes!")    
    print(f"\n   Missing from climate: {smap_keys - climate_keys}")    
    print(f"   Missing from physical: {smap_keys - physical_keys}")    
    # print(f"   Missing from humidity: {smap_keys - humidity_keys}")    
    print(f"   Missing from smap: {climate_keys - smap_keys}")

📊 Número de keys por dictionary:
  - climate_dict:  18
  - physical_dict: 18
  - smap_dict:     18

✅ Keys comunes a los 4 dictionaries: 18
   ['Anduña', 'Bailin', 'Deza', 'Flamisell', 'Garona', 'Isuela', 'Larraun', 'Nela', 'Oroncillo', 'Rudron', 'Sangüesa', 'Subialde', 'Tiron', 'Ubagua', 'Urrobi', 'Vallfarrera', 'Yanguas', 'Zatoya']

In [81]:
# DEBUG 2: Verificar tamaños de datos
if len(common_keys) > 0:    
    test_basin = list(common_keys)[0]    
    print(f"🧪 Testing con: {test_basin}\n")    
    print("Shapes de cada dataset:")    
    print(f"  climate:  {climate_dict[test_basin].shape}")    
    print(f"  physical: {physical_dict[test_basin].shape}")    
    # print(f"  humidity: {humidity_dict[test_basin].shape}")    
    print(f"  smap:     {smap_dict[test_basin].shape}")    
    print(f"\nRangos de fechas:")    
    print(f"  climate Date: {climate_dict[test_basin]['Date'].min()} to {climate_dict[test_basin]['Date'].max()}")    
    # print(f"  humidity dia: {humidity_dict[test_basin]['dia'].min()} to {humidity_dict[test_basin]['dia'].max()}")    
    print(f"  smap date:    {smap_dict[test_basin]['date'].min()} to {smap_dict[test_basin]['date'].max()}")

🧪 Testing con: Isuela

Shapes de cada dataset:
  climate:  (1826, 21)
  physical: (1, 39)
  smap:     (1826, 11)

Rangos de fechas:
  climate Date: 2020-10-01 00:00:00 to 2025-09-30 00:00:00
  smap date:    2020-09-30 00:00:00 to 2025-09-30 00:00:00

In [82]:
# DEBUG 3: Verificar overlap de fechas
if len(common_keys) > 0:    
    climate_dates = set(climate_dict[test_basin]['Date'].dt.date)    
    # humidity_dates = set(humidity_dict[test_basin]['dia'].dt.date)    
    smap_dates = set(smap_dict[test_basin]['date'].dt.date)    
    print("📅 Overlap de fechas:")    
    # print(f"  Climate & Humidity: {len(climate_dates & humidity_dates):4d} días")    
    print(f"  Climate & SMAP:     {len(climate_dates & smap_dates):4d} días")    
    # print(f"  Humidity & SMAP:    {len(humidity_dates & smap_dates):4d} días")    
    print(f"  \n  🎯 LOS 3 JUNTOS:    {len(climate_dates  & smap_dates):4d} días")    
    if len(climate_dates & smap_dates) == 0:        
        print("\n⚠️  PROBLEMA CRÍTICO: No hay overlap de fechas entre los 3 datasets!")        
        print("\n   Esto explica por qué join_dict está vacío.")        
        print("\n   Primeras fechas de cada dataset:")        
        print(f"   - Climate:  {sorted(climate_dates)[:5]}")        
        # print(f"   - Humidity: {sorted(humidity_dates)[:5]}")        
        print(f"   - SMAP:     {sorted(smap_dates)[:5]}")

📅 Overlap de fechas:
  Climate & SMAP:     1825 días

  🎯 LOS 3 JUNTOS:    1825 días

In [83]:
# DEBUG 4: Test merge SIN SMAP (solo climate + humidity + physical)
# if len(common_keys) > 0:    
#     test_df_climate = climate_dict[test_basin].copy()    
#     # test_df_humidity = humidity_dict[test_basin].copy()    
#     test_df_physical = physical_dict[test_basin].copy()    
#     # Merge climate + humidity    
#     # test_merged_1 = pd.merge(test_df_climate, test_df_humidity, left_on="Date", right_on="dia", how="inner")    
#     # print(f"✓ Merge climate + humidity: {test_merged_1.shape}")    
#     # Clean up    if 'Area_nm_x' in test_merged_1.columns:        
#     # test_merged_1["Area_nm"] = test_merged_1["Area_nm_x"].fillna(test_merged_1["Area_nm_y"])        
#     # test_merged_1.drop(columns=["Area_nm_x", "Area_nm_y", "dia"], inplace=True)    
#     # Merge with physical    
#     test_merged_2 = pd.merge(test_merged_1, test_df_physical, on="Area_nm", how="inner")    
#     print(f"✓ Merge + physical: {test_merged_2.shape}")    
#     if test_merged_2.shape[0] > 0:        
#         print(f"\n✅ Merge SIN SMAP funciona! ({test_merged_2.shape[0]} filas)")        
#         print("   El problema es específico de SMAP.")    
#     else:        
#         print("\n⚠️  Merge falla incluso SIN SMAP")

In [84]:
# join_dict = {}

# # Include all four data sources in the merge
# for key in climate_dict.keys() & physical_dict.keys() & humidity_dict.keys() & smap_dict.keys():
#     df_climate = climate_dict[key]
#     df_physical = physical_dict[key]
#     df_humidity = humidity_dict[key]
#     df_smap = smap_dict[key]

#     # 1️⃣ Merge climate and humidity by Date/dia
#     merged = pd.merge(
#         df_climate,
#         df_humidity,
#         left_on="Date",
#         right_on="dia",
#         how="inner"
#     )

#     # Clean up duplicate Area_nm columns
#     merged["Area_nm"] = merged["Area_nm_x"].fillna(merged["Area_nm_y"])
#     merged.drop(columns=["Area_nm_x", "Area_nm_y", "dia"], inplace=True)

#     # 2️⃣ Merge with SMAP data by Date/date
#     merged = pd.merge(
#         merged,
#         df_smap,
#         left_on="Date",
#         right_on="date",
#         how="inner"
#     )

#     # Clean up duplicate Area_nm columns and date column
#     merged["Area_nm"] = merged["Area_nm_x"].fillna(merged["Area_nm_y"])
#     merged.drop(columns=["Area_nm_x", "Area_nm_y", "date"], inplace=True, errors='ignore')

#     # 3️⃣ Merge with physical properties by Area_nm
#     merged = pd.merge(
#         merged,
#         df_physical,
#         on="Area_nm",
#         how="inner"
#     )

#     # Save in the new dict
#     join_dict[key] = merged

In [85]:
climate_dict.get("Isuela").count()

et0         1826
Hrav        1826
Year        1826
Hrmin       1826
SolarRad    1826
yav         1826
tmin        1826
wvmax       1826
P           1826
qmin        1826
Date        1826
Jdate       1826
qav         1826
tav         1826
ymax        1826
ymin        1826
wv          1826
Hrmax       1826
tmax        1826
qmax        1826
Area_nm     1826
dtype: int64

In [86]:
climate_dict.get("Anduña").count()

et0         1826
Hrav        1826
Year        1826
Hrmin       1826
SolarRad    1826
yav         1826
tmin        1826
wvmax       1826
P           1826
qmin        1826
Date        1826
Jdate       1826
qav         1826
tav         1826
ymax        1826
ymin        1826
wv          1826
Hrmax       1826
tmax        1826
qmax        1826
Area_nm     1826
dtype: int64

In [87]:
physical_dict.get("Isuela").count()

CN_ponderado      1
CN_DT             1
n                 1
DT_n              1
area_cuenca       1
longitud_total    1
z_min             1
z_max             1
mean_sand         1
mean_silt         1
mean_clay         1
soil_type         1
ks_st             1
thetas_st         1
thetar_st         1
thau_st           1
swcfc_st          1
swcpwp_st         1
mean_ks           1
DT_ks             1
mean_thetas       1
DT_thetas         1
mean_thetar       1
DT_thetar         1
mean_thau         1
DT_thau           1
mean_swcfc        1
DT_swcfc          1
mean_swcpwp       1
DT_swcpwp         1
lon_min           1
lon_max           1
lat_min           1
lat_max           1
x_min_25830       1
x_max_25830       1
y_min_25830       1
y_max_25830       1
Area_nm           1
dtype: int64

In [88]:
physical_dict.get("Anduña").count()

CN_ponderado      1
CN_DT             1
n                 1
DT_n              1
area_cuenca       1
longitud_total    1
z_min             1
z_max             1
mean_sand         1
mean_silt         1
mean_clay         1
soil_type         1
ks_st             1
thetas_st         1
thetar_st         1
thau_st           1
swcfc_st          1
swcpwp_st         1
mean_ks           1
DT_ks             1
mean_thetas       1
DT_thetas         1
mean_thetar       1
DT_thetar         1
mean_thau         1
DT_thau           1
mean_swcfc        1
DT_swcfc          1
mean_swcpwp       1
DT_swcpwp         1
lon_min           1
lon_max           1
lat_min           1
lat_max           1
x_min_25830       1
x_max_25830       1
y_min_25830       1
y_max_25830       1
Area_nm           1
dtype: int64

In [89]:
smap_dict.get("Isuela").count()

date               1826
sm_rootzone_av     1826
sm_rootzone_dif    1826
sm_rootzone_max    1826
sm_rootzone_min    1826
sm_surface_av      1826
sm_surface_dif     1826
sm_surface_max     1826
sm_surface_min     1826
q0_r               1826
q0_s               1826
dtype: int64

In [90]:
smap_dict.get("Anduña").count()

date               1826
sm_rootzone_av     1826
sm_rootzone_dif    1826
sm_rootzone_max    1826
sm_rootzone_min    1826
sm_surface_av      1826
sm_surface_dif     1826
sm_surface_max     1826
sm_surface_min     1826
q0_r               1826
q0_s               1826
dtype: int64

In [92]:
# join_dict.get("Anduña").count()

In [94]:
# join_dict.get("Isuela").count()

In [95]:
join_dict = {}

# Iterar solo sobre claves presentes en climate, physical y smap
for key in climate_dict.keys() & physical_dict.keys() & smap_dict.keys():
    df_climate = climate_dict[key]
    df_physical = physical_dict[key]
    df_smap = smap_dict[key]

    # 1️⃣ Merge climate y SMAP por Date/date
    merged = pd.merge(
        df_climate,
        df_smap,
        left_on="Date",
        right_on="date",
        how="inner"
    )

    # Resolver duplicados de Area_nm (si existen) y eliminar columna de fecha de SMAP
    if "Area_nm_x" in merged.columns or "Area_nm_y" in merged.columns:
        merged["Area_nm"] = merged.get("Area_nm_x").fillna(merged.get("Area_nm_y"))
        merged.drop(columns=["Area_nm_x", "Area_nm_y"], inplace=True, errors="ignore")
    merged.drop(columns=["date"], inplace=True, errors="ignore")

    # 2️⃣ Merge con propiedades físicas por Area_nm
    merged = pd.merge(
        merged,
        df_physical,
        on="Area_nm",
        how="inner"
    )

    # Guardar resultado
    join_dict[key] = merged

# Save merged data

In [96]:
base_path = "../../data/clean/merged_data/"


for k, v_df in join_dict.items():
    # v_df.reindex(columns=sorted(list(v_df.columns))).to_json(f"{base_path}{k}-without-outliers.json", orient="records", indent=4) # WITHOUT OUTLIERS
    v_df.reindex(columns=sorted(list(v_df.columns))).to_json(f"{base_path}{k}-with-outliers.json", orient="records", indent=4) # WITH OUTLIERS


#join_dict.reindex(columns=sorted(list(join_dict.columns))).to_json(f"{base_path}merged_data.json", orient="records", indent=4)

In [97]:
# Reconstruir el diccionario
join_dict_restored = {}

for filename in os.listdir(base_path):
    if filename.endswith("-with-outliers.json"):
        # El nombre del archivo sin extensión
        basin_name = os.path.splitext(filename)[0]
        
        # Leer el JSON como DataFrame
        df = pd.read_json(os.path.join(base_path, filename), orient="records")
        
        join_dict_restored[basin_name] = df

# Ahora climate_dict_restored tiene la misma estructura que el original
print(join_dict_restored.keys())

dict_keys(['Tiron-with-outliers', 'Oroncillo-with-outliers', 'Rudron-with-outliers', 'Larraun-with-outliers', 'Zatoya-with-outliers', 'Flamisell-with-outliers', 'Vallfarrera-with-outliers', 'Yanguas-with-outliers', 'Garona-with-outliers', 'Urrobi-with-outliers', 'Anduña-with-outliers', 'Bailin-with-outliers', 'Nela-with-outliers', 'Deza-with-outliers', 'Ubagua-with-outliers', 'Isuela-with-outliers', 'Subialde-with-outliers', 'Sangüesa-with-outliers'])

# Check duplicated values:

In [98]:
len(join_dict_restored["Flamisell-with-outliers"])

1825

In [99]:
join_dict_restored["Flamisell-with-outliers"].duplicated(subset="Date").sum()

np.int64(0)

In [100]:
join_dict_restored["Flamisell-with-outliers"].head()

,Area_nm,CN_DT,CN_ponderado,DT_ks,DT_n,DT_swcfc,DT_swcpwp,DT_thau,DT_thetar,DT_thetas,Date,Hrav,Hrmax,Jdate,P,SolarRad,Year,area_cuenca,et0,ks_st,lat_max,lat_min,lon_max,lon_min,longitud_total,mean_clay,mean_ks,mean_sand,mean_silt,mean_swcfc,mean_swcpwp,mean_thau,mean_thetar,mean_thetas,n,q0_r,q0_s,qav,qmax,qmin,sm_rootzone_av,sm_rootzone_dif,sm_rootzone_max,sm_rootzone_min,sm_surface_av,sm_surface_dif,sm_surface_max,sm_surface_min,soil_type,swcfc_st,swcpwp_st,tav,thau_st,thetar_st,thetas_st,tmax,tmin,wv,x_max_25830,x_min_25830,y_max_25830,y_min_25830,yav,ymax,ymin,z_max,z_min
0,Flamisell,6.495779,84.836084,2.11437,0.030173,0.008723,0.029699,22400.48278,0.004075,0.00899,2020-10-01,64,92,275,0.0,15.2,2020,6.765123e+07,2.94,10.4,42.555635,42.44043,1.029439,0.916032,17336.719144,21.812624,9.824065,34.74975,42.17181,0.346355,0.122798,3500.313769,0.078872,0.427968,0.114143,0.222751,0.173787,1.29,1.33,1.243,0.223703,0.001720,0.224471,0.222751,0.193095,0.029494,0.203281,0.173787,Loam,0.344061,0.115188,15.3,960.86766,0.078,0.43,25.0,7.6,1.9,338227.5,328602.5,4713352.5,4700782.5,0.24,0.24,0.23,2962.366943,1275.26001
1,Flamisell,6.495779,84.836084,2.11437,0.030173,0.008723,0.029699,22400.48278,0.004075,0.00899,2020-10-02,88,99,276,70.8,2.0,2020,6.765123e+07,0.44,10.4,42.555635,42.44043,1.029439,0.916032,17336.719144,21.812624,9.824065,34.74975,42.17181,0.346355,0.122798,3500.313769,0.078872,0.427968,0.114143,0.223453,0.194828,3.98,7.68,1.243,0.243176,0.030883,0.254336,0.223453,0.268455,0.149117,0.343945,0.194828,Loam,0.344061,0.115188,11.0,960.86766,0.078,0.43,15.8,3.9,1.1,338227.5,328602.5,4713352.5,4700782.5,0.44,0.63,0.23,2962.366943,1275.26001
2,Flamisell,6.495779,84.836084,2.11437,0.030173,0.008723,0.029699,22400.48278,0.004075,0.00899,2020-10-03,81,99,277,1.4,7.1,2020,6.765123e+07,1.17,10.4,42.555635,42.44043,1.029439,0.916032,17336.719144,21.812624,9.824065,34.74975,42.17181,0.346355,0.122798,3500.313769,0.078872,0.427968,0.114143,0.251821,0.254373,2.96,3.65,2.629,0.249871,0.004003,0.251821,0.247817,0.248451,0.014549,0.254610,0.240061,Loam,0.344061,0.115188,8.7,960.86766,0.078,0.43,14.4,4.6,0.9,338227.5,328602.5,4713352.5,4700782.5,0.40,0.45,0.37,2962.366943,1275.26001
3,Flamisell,6.495779,84.836084,2.11437,0.030173,0.008723,0.029699,22400.48278,0.004075,0.00899,2020-10-04,77,98,278,0.6,12.7,2020,6.765123e+07,2.00,10.4,42.555635,42.44043,1.029439,0.916032,17336.719144,21.812624,9.824065,34.74975,42.17181,0.346355,0.122798,3500.313769,0.078872,0.427968,0.114143,0.247165,0.237465,2.40,2.63,2.201,0.244960,0.004391,0.247165,0.242774,0.231298,0.012647,0.237465,0.224818,Loam,0.344061,0.115188,9.7,960.86766,0.078,0.43,17.2,4.2,1.1,338227.5,328602.5,4713352.5,4700782.5,0.35,0.37,0.33,2962.366943,1275.26001
4,Flamisell,6.495779,84.836084,2.11437,0.030173,0.008723,0.029699,22400.48278,0.004075,0.00899,2020-10-05,74,97,279,0.0,14.9,2020,6.765123e+07,2.31,10.4,42.555635,42.44043,1.029439,0.916032,17336.719144,21.812624,9.824065,34.74975,42.17181,0.346355,0.122798,3500.313769,0.078872,0.427968,0.114143,0.242295,0.224111,2.09,2.20,1.987,0.240676,0.003575,0.242295,0.238721,0.222479,0.011157,0.227353,0.216196,Loam,0.344061,0.115188,10.0,960.86766,0.078,0.43,19.7,2.4,1.2,338227.5,328602.5,4713352.5,4700782.5,0.32,0.33,0.31,2962.366943,1275.26001

In [101]:
join_dict_restored["Isuela-with-outliers"].count()

Area_nm         1825
CN_DT           1825
CN_ponderado    1825
DT_ks           1825
DT_n            1825
                ...
yav             1825
ymax            1825
ymin            1825
z_max           1825
z_min           1825
Length: 69, dtype: int64

In [102]:
# DataFrame base
df = join_dict_restored["Tiron-with-outliers"][["Date", "Jdate"]].copy()

# Asegurarse de que Date es datetime (si ya lo es, esto no cambia nada)
# df["Date"] = pd.to_datetime(df["Date"])

# # 1. Conteo simple de filas por año
# counts_by_year = (
#     df.groupby(df["Date"].dt.year)
#       .size()
#       .reset_index(name="count")
#       .rename(columns={"Date": "Year"})
#       .sort_values("Date")
# )

# Alternativa más explícita nombrando la columna Year
counts_by_year = (
    df.assign(Year=df["Date"].dt.year)
      .groupby("Year")
      .size()
      .reset_index(name="count")
      .sort_values("Year")
)

print(counts_by_year)

   Year  count
0  2020     92
1  2021    365
2  2022    365
3  2023    365
4  2024    366
5  2025    272

In [103]:
pd.set_option("display.max_rows", None)

In [104]:
y_lst = [2020, 2021, 2022, 2023, 2024, 2025]
for cuenca in join_dict_restored.keys():
    for y in y_lst: 
        cnt = join_dict_restored[f"{cuenca}"]["Date"][(join_dict_restored[f"{cuenca}"]["Date"]>= f"{y}-01-01") & (join_dict_restored["Flamisell-with-outliers"]["Date"]< f"{y+1}-01-01")].count()
        print(cuenca, y, '-->', cnt)

Tiron-with-outliers 2020 --> 92
Tiron-with-outliers 2021 --> 365
Tiron-with-outliers 2022 --> 365
Tiron-with-outliers 2023 --> 365
Tiron-with-outliers 2024 --> 366
Tiron-with-outliers 2025 --> 272
Oroncillo-with-outliers 2020 --> 92
Oroncillo-with-outliers 2021 --> 365
Oroncillo-with-outliers 2022 --> 365
Oroncillo-with-outliers 2023 --> 365
Oroncillo-with-outliers 2024 --> 366
Oroncillo-with-outliers 2025 --> 272
Rudron-with-outliers 2020 --> 92
Rudron-with-outliers 2021 --> 365
Rudron-with-outliers 2022 --> 365
Rudron-with-outliers 2023 --> 365
Rudron-with-outliers 2024 --> 366
Rudron-with-outliers 2025 --> 272
Larraun-with-outliers 2020 --> 92
Larraun-with-outliers 2021 --> 365
Larraun-with-outliers 2022 --> 365
Larraun-with-outliers 2023 --> 365
Larraun-with-outliers 2024 --> 366
Larraun-with-outliers 2025 --> 272
Zatoya-with-outliers 2020 --> 92
Zatoya-with-outliers 2021 --> 365
Zatoya-with-outliers 2022 --> 365
Zatoya-with-outliers 2023 --> 365
Zatoya-with-outliers 2024 --> 366
Zatoya-with-outliers 2025 --> 272
Flamisell-with-outliers 2020 --> 92
Flamisell-with-outliers 2021 --> 365
Flamisell-with-outliers 2022 --> 365
Flamisell-with-outliers 2023 --> 365
Flamisell-with-outliers 2024 --> 366
Flamisell-with-outliers 2025 --> 272
Vallfarrera-with-outliers 2020 --> 92
Vallfarrera-with-outliers 2021 --> 365
Vallfarrera-with-outliers 2022 --> 365
Vallfarrera-with-outliers 2023 --> 365
Vallfarrera-with-outliers 2024 --> 366
Vallfarrera-with-outliers 2025 --> 272
Yanguas-with-outliers 2020 --> 92
Yanguas-with-outliers 2021 --> 365
Yanguas-with-outliers 2022 --> 365
Yanguas-with-outliers 2023 --> 365
Yanguas-with-outliers 2024 --> 366
Yanguas-with-outliers 2025 --> 272
Garona-with-outliers 2020 --> 92
Garona-with-outliers 2021 --> 365
Garona-with-outliers 2022 --> 365
Garona-with-outliers 2023 --> 365
Garona-with-outliers 2024 --> 366
Garona-with-outliers 2025 --> 272
Urrobi-with-outliers 2020 --> 92
Urrobi-with-outliers 2021 --> 365
Urrobi-with-outliers 2022 --> 365
Urrobi-with-outliers 2023 --> 365
Urrobi-with-outliers 2024 --> 366
Urrobi-with-outliers 2025 --> 272
Anduña-with-outliers 2020 --> 92
Anduña-with-outliers 2021 --> 365
Anduña-with-outliers 2022 --> 365
Anduña-with-outliers 2023 --> 365
Anduña-with-outliers 2024 --> 366
Anduña-with-outliers 2025 --> 272
Bailin-with-outliers 2020 --> 92
Bailin-with-outliers 2021 --> 365
Bailin-with-outliers 2022 --> 365
Bailin-with-outliers 2023 --> 365
Bailin-with-outliers 2024 --> 366
Bailin-with-outliers 2025 --> 272
Nela-with-outliers 2020 --> 92
Nela-with-outliers 2021 --> 365
Nela-with-outliers 2022 --> 365
Nela-with-outliers 2023 --> 365
Nela-with-outliers 2024 --> 366
Nela-with-outliers 2025 --> 272
Deza-with-outliers 2020 --> 92
Deza-with-outliers 2021 --> 365
Deza-with-outliers 2022 --> 365
Deza-with-outliers 2023 --> 365
Deza-with-outliers 2024 --> 366
Deza-with-outliers 2025 --> 272
Ubagua-with-outliers 2020 --> 92
Ubagua-with-outliers 2021 --> 365
Ubagua-with-outliers 2022 --> 365
Ubagua-with-outliers 2023 --> 365
Ubagua-with-outliers 2024 --> 366
Ubagua-with-outliers 2025 --> 272
Isuela-with-outliers 2020 --> 92
Isuela-with-outliers 2021 --> 365
Isuela-with-outliers 2022 --> 365
Isuela-with-outliers 2023 --> 365
Isuela-with-outliers 2024 --> 366
Isuela-with-outliers 2025 --> 272
Subialde-with-outliers 2020 --> 92
Subialde-with-outliers 2021 --> 365
Subialde-with-outliers 2022 --> 365
Subialde-with-outliers 2023 --> 365
Subialde-with-outliers 2024 --> 366
Subialde-with-outliers 2025 --> 272
Sangüesa-with-outliers 2020 --> 92
Sangüesa-with-outliers 2021 --> 365
Sangüesa-with-outliers 2022 --> 365
Sangüesa-with-outliers 2023 --> 365
Sangüesa-with-outliers 2024 --> 366
Sangüesa-with-outliers 2025 --> 272

## Check nulls in columns

In [105]:
for k, v in join_dict.items():
    print("\n", k)
    #print(climate_dict[k].isnull().sum())
    print(join_dict[k].isnull().mean().round(3) * 100) # % of null values

 Isuela
et0                0.0
Hrav               0.0
Year               0.0
Hrmin              0.0
SolarRad           0.0
yav                0.0
tmin               0.0
wvmax              0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Oroncillo
et0                0.0
Hrav               0.0
Year               0.0
Hrmin              0.0
SolarRad           0.0
yav                0.0
tmin               0.0
wvmax              0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Ubagua
et0                0.0
Hrav               0.0
Year               0.0
Hrmin              0.0
SolarRad           0.0
yav                0.0
tmin               0.0
wvmax              0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Sangüesa
et0                0.0
Hrav               0.0
Year               0.0
Hrmin              0.0
SolarRad           0.0
yav                0.0
tmin               0.0
wvmax              0.0
P                  0.0
qmin               2.0
Date               0.0
Jdate              0.0
qav                2.2
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               2.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Zatoya
et0                0.0
Hrav               0.0
Year               0.0
Hrmin              0.0
SolarRad           0.0
yav                0.0
tmin               0.0
wvmax              0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Flamisell
et0                0.0
Hrav               0.0
Year               0.0
SolarRad           0.0
yav                0.0
tmin               0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Vallfarrera
et0                0.0
Hrav               0.0
Year               0.0
SolarRad           0.0
yav                0.0
tmin               0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Tiron
et0                0.0
Hrav               0.0
Year               0.0
Hrmin              0.0
SolarRad           0.0
yav                0.0
tmin               0.0
wvmax              0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Garona
et0                0.0
Hrav               0.0
Year               0.0
SolarRad           0.0
yav                0.0
tmin               0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Anduña
et0                0.0
Hrav               0.0
Year               0.0
Hrmin              0.0
SolarRad           0.0
yav                0.0
tmin               0.0
wvmax              0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Urrobi
et0                0.0
Hrav               0.0
Year               0.0
Hrmin              0.0
SolarRad           0.0
yav                0.0
tmin               0.0
wvmax              0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Yanguas
et0                0.0
Hrav               0.0
Year               0.0
Hrmin              0.0
SolarRad           0.0
yav                0.0
tmin               0.0
wvmax              0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0
DT_n               0.0
area_cuenca        0.0
longitud_total     0.0
z_min              0.0
z_max              0.0
mean_sand          0.0
mean_silt          0.0
mean_clay          0.0
soil_type          0.0
ks_st              0.0
thetas_st          0.0
thetar_st          0.0
thau_st            0.0
swcfc_st           0.0
swcpwp_st          0.0
mean_ks            0.0
DT_ks              0.0
mean_thetas        0.0
DT_thetas          0.0
mean_thetar        0.0
DT_thetar          0.0
mean_thau          0.0
DT_thau            0.0
mean_swcfc         0.0
DT_swcfc           0.0
mean_swcpwp        0.0
DT_swcpwp          0.0
lon_min            0.0
lon_max            0.0
lat_min            0.0
lat_max            0.0
x_min_25830        0.0
x_max_25830        0.0
y_min_25830        0.0
y_max_25830        0.0
dtype: float64

 Rudron
et0                0.0
Hrav               0.0
Year               0.0
Hrmin              0.0
SolarRad           0.0
yav                0.0
tmin               0.0
wvmax              0.0
P                  0.0
qmin               0.0
Date               0.0
Jdate              0.0
qav                0.0
tav                0.0
ymax               0.0
ymin               0.0
wv                 0.0
Hrmax              0.0
tmax               0.0
qmax               0.0
Area_nm            0.0
sm_rootzone_av     0.0
sm_rootzone_dif    0.0
sm_rootzone_max    0.0
sm_rootzone_min    0.0
sm_surface_av      0.0
sm_surface_dif     0.0
sm_surface_max     0.0
sm_surface_min     0.0
q0_r               0.0
q0_s               0.0
CN_ponderado       0.0
CN_DT              0.0
n                  0.0